# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

      - image: circleci/postgres:11.2-alpine-postgis
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: server_wallet_test
          POSTGRES_PASSWORD: ''

    working_directory: ~/apps

    steps:
      - checkout

      - run: npx lerna bootstrap
      - run: npx lerna run prepare

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      # run tests!
      - run: npx lerna run test:ci --stream --concurrency 2 --since origin/master
